import { connectMongoDB } from "@/app/lib/mongodb";
import { NextResponse } from "next/server";
import bcrypt from "bcrypt";
import { User } from "@/app/models/User";

export async function POST(req) {
  try {
    const { firstName, lastName, email, password, weeksIntoPregnancy, allergies, diet } = await req.json();

    const salt = await bcrypt.genSalt();
    const hashedPassword = await bcrypt.hash(password, salt);

    await connectMongoDB();
    await User.create({
      firstName,
      lastName,
      email,
      password: hashedPassword,
      weeksIntoPregnancy,
      allergies,
      diet,
      favoriteRecipes: [],
      allWeeksNutrientInfo: [
        {
            week: 1,
            addedIngredients: [],
            eatenRecipes: [],
            nutrientContent: {
                "Folic Acid": 0,
                "Omega-3 Fatty Acids": 0,
                "Vitamin D": 0,
                "Iron": 0,
            },
        },
        {
          week: 2,
          addedIngredients: [],
          eatenRecipes: [],
          nutrientContent: {
              "Folic Acid": 0,
              "Omega-3 Fatty Acids": 0,
              "Vitamin D": 0,
              "Iron": 0,
          },
      },
      {
        week: 3,
        addedIngredients: [],
        eatenRecipes: [],
        nutrientContent: {
            "Folic Acid": 0,
            "Omega-3 Fatty Acids": 0,
            "Vitamin D": 0,
            "Iron": 0,
        },
    },
      {
        week: 4,
        addedIngredients: [],
        eatenRecipes: [],
        nutrientContent: {
            "Folic Acid": 0,
            "Omega-3 Fatty Acids": 0,
            "Vitamin D": 0,
            "Iron": 0,
        },
    },
    {
      week: 5,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Vitamin C": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin B6": 0,
      },
    },
    {
      week: 6,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Vitamin C": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin B6": 0,
      },
    },
    {
      week: 7,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Vitamin C": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin B6": 0,
      },
    },
    {
      week: 8,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Vitamin C": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin B6": 0,
      },
    },
    {
      week: 9,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin A": 0,
          "Vitamin B12": 0,
          "Choline": 0,
          "Iodine": 0,
          "Vitamin B9": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 10,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin A": 0,
          "Vitamin B12": 0,
          "Choline": 0,
          "Iodine": 0,
          "Vitamin B9": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 11,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin A": 0,
          "Vitamin B12": 0,
          "Choline": 0,
          "Iodine": 0,
          "Vitamin B9": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 12,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin A": 0,
          "Vitamin B12": 0,
          "Choline": 0,
          "Iodine": 0,
          "Vitamin B9": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 13,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Omega-3 Fatty Acids": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Vitamin B3": 0,
          "Vitamin B5": 0,
      },
    },
    {
      week: 14,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Omega-3 Fatty Acids": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Vitamin B3": 0,
          "Vitamin B5": 0,
      },
    },
    {
      week: 15,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Omega-3 Fatty Acids": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Vitamin B3": 0,
          "Vitamin B5": 0,
      },
    },
    {
      week: 16,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Omega-3 Fatty Acids": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Vitamin B3": 0,
          "Vitamin B5": 0,
      },
    },
    {
      week: 17,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
      },
    },
    {
      week: 18,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
      },
    },
    {
      week: 19,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
      },
    },
    {
      week: 20,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
      },
    },
    {
      week: 21,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B3": 0,
          "Vitamin B5": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Iron": 0,
          "Calcium": 0,
          "Magnesium": 0,
      },
    },
    {
      week: 22,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B3": 0,
          "Vitamin B5": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Iron": 0,
          "Calcium": 0,
          "Magnesium": 0,
      },
    },
    {
      week: 23,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B3": 0,
          "Vitamin B5": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Iron": 0,
          "Calcium": 0,
          "Magnesium": 0,
      },
    },
    {
      week: 24,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B3": 0,
          "Vitamin B5": 0,
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Iron": 0,
          "Calcium": 0,
          "Magnesium": 0,
      },
    },
    {
      week: 25,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Vitamin K": 0,
          "Vitamin B9": 0,
          "Omega-3 Fatty Acids": 0,
          "Iron": 0,
          "Choline": 0,
          "Iodine": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 26,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Vitamin K": 0,
          "Vitamin B9": 0,
          "Omega-3 Fatty Acids": 0,
          "Iron": 0,
          "Choline": 0,
          "Iodine": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 27,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Vitamin K": 0,
          "Vitamin B9": 0,
          "Omega-3 Fatty Acids": 0,
          "Iron": 0,
          "Choline": 0,
          "Iodine": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 28,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Vitamin K": 0,
          "Vitamin B9": 0,
          "Omega-3 Fatty Acids": 0,
          "Iron": 0,
          "Choline": 0,
          "Iodine": 0,
          "Coenzyme Q10": 0,
      },
    },
    {
      week: 29,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B6": 0,
          "Calcium": 0,
          "Magnesium": 0,
          "Potassium": 0,
      },
    },
    {
      week: 30,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B6": 0,
          "Calcium": 0,
          "Magnesium": 0,
          "Potassium": 0,
      },
    },
    {
      week: 31,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B6": 0,
          "Calcium": 0,
          "Magnesium": 0,
          "Potassium": 0,
      },
    },
    {
      week: 32,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Zinc": 0,
          "Selenium": 0,
          "Vitamin B1": 0,
          "Vitamin B2": 0,
          "Vitamin B6": 0,
          "Calcium": 0,
          "Magnesium": 0,
          "Potassium": 0,
      },
    },
    {
      week: 33,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,

      },
    },
    {
      week: 34,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,

      },
    },
    {
      week: 35,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,

      },
    },
    {
      week: 36,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Vitamin B7": 0,
          "Vitamin B9": 0,
          "Vitamin B12": 0,
          "Vitamin C": 0,
          "Vitamin D": 0,
          "Vitamin E": 0,
          "Iron": 0,
          "Vitamin K": 0,

      },
    },
    {
      week: 37,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin D": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Omega-3 Fatty Acids": 0,
      },
    },
    {
      week: 38,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin D": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Omega-3 Fatty Acids": 0,
      },
    },
    {
      week: 39,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin D": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Omega-3 Fatty Acids": 0,
      },
    },
    {
      week: 40,
      addedIngredients: [],
      eatenRecipes: [],
      nutrientContent: {
          "Calcium": 0,
          "Magnesium": 0,
          "Zinc": 0,
          "Vitamin E": 0,
          "Vitamin D": 0,
          "Iron": 0,
          "Vitamin K": 0,
          "Omega-3 Fatty Acids": 0,
      },
    },    
  ]
    });

    return NextResponse.json({ message: "User signed up." }, { status: 201 });
  } catch (error) {
    return NextResponse.json(
      { message: "An error occurred during user sign up." },
      { status: 500 }
    );
  }
}